Consistency tweaks

diff --git a/scripts/afdownsample b/scripts/afdownsample
--- a/scripts/afdownsample
+++ b/scripts/afdownsample
@@ -39,12 +39,12 @@ while getopts :d:h OPT; do
             exit 0
             ;;
         \?)
-            echo "$PROG: illegal option -- $OPTARG"
+            echo "${PROG}: illegal option -- $OPTARG"
             usage
             exit 1
             ;;
         :)
-            echo "$PROG: -$OPTARG requires an argument"
+            echo "${PROG}: -${OPTARG} requires an argument"
             usage
             exit 1
             ;;
@@ -53,13 +53,13 @@ done
 shift $((OPTIND-1))
 
 if [[ $# -gt 0 ]]; then
-    echo "$PROG: illegal argument -- $1"
+    echo "${PROG}: illegal argument -- $1"
     usage
     exit 1
 fi
 
 # Check for sox.
-command -v sox >/dev/null 2>&1 || { echo "$PROG: sox: command not found"; exit 1; }
+command -v sox >/dev/null 2>&1 || { echo "${PROG}: sox: command not found"; exit 1; }
 
 # Check if directory exists.
 [[ -d "$DIR" ]] || { echo "${PROG}: ${DIR}: No such directory"; usage; exit 1; }
@@ -88,5 +88,5 @@ while IFS= read -r -d '' file; do
 done < <(find "$DIR" -depth 1 -type f \( -iname "*.aiff" -or -iname "*.aif" -or -iname "*.wav" -or -iname "*.flac" \) -print0)
 
 if [[ $COUNT -eq 0 ]]; then
-    echo "$PROG: No high resolution audio files found"
+    echo "${PROG}: No high resolution audio files found"
 fi
diff --git a/scripts/backup-itunes b/scripts/backup-itunes
--- a/scripts/backup-itunes
+++ b/scripts/backup-itunes
@@ -39,12 +39,12 @@ while getopts :nvh OPT; do
             exit 0
             ;;
         \?)
-            echo "$PROG: illegal option -- $OPTARG"
+            echo "${PROG}: illegal option -- $OPTARG"
             usage
             exit 1
             ;;
         :)
-            echo "$PROG: -$OPTARG requires an argument"
+            echo "${PROG}: -${OPTARG} requires an argument"
             usage
             exit 1
             ;;
@@ -53,13 +53,13 @@ done
 shift $((OPTIND-1))
 
 if [[ $# -gt 0 ]]; then
-    echo "$PROG: illegal argument -- $1"
+    echo "${PROG}: illegal argument -- $1"
     usage
     exit 1
 fi
 
 # Check rsync version.
-[[ $(rsync --version) =~ version\ 3\.1 ]] || { echo "$PROG: rsync 3.1.0 or later is required"; exit 1; }
+[[ $(rsync --version) =~ version\ 3\.1 ]] || { echo "${PROG}: rsync 3.1.0 or later is required"; exit 1; }
 
 # Check if required directories exist.
 [[ -d "$SRC" ]] || { echo "${PROG}: ${SRC}: No such directory"; exit 1; }
