Make script more verbose; indentation 2 spaces

diff --git a/scripts/backup-itunes b/scripts/backup-itunes
--- a/scripts/backup-itunes
+++ b/scripts/backup-itunes
@@ -10,8 +10,8 @@
 
 
 usage() {
-    echo "usage: $PROG [-n] [-v]"
-    }
+  echo "usage: $PROG [-n] [-v]"
+}
 
 
 PROG=${0##*/}
@@ -24,38 +24,38 @@ SRC="${HOME}/Music/iTunes"
 # Parse command line options.
 OPTIND=1
 while getopts :nvh OPT; do
-    case $OPT in
-        n)
-            RSYNC_OPTIONS+="--dry-run "
-            ;;
-        v)
-            RSYNC_OPTIONS+="--verbose "
-            ;;
-        h)
-            usage
-            echo
-            echo "  -n  Show what would have been backed up"
-            echo "  -v  Increase verbosity"
-            exit 0
-            ;;
-        \?)
-            echo "${PROG}: illegal option -- $OPTARG"
-            usage
-            exit 1
-            ;;
-        :)
-            echo "${PROG}: -${OPTARG} requires an argument"
-            usage
-            exit 1
-            ;;
-    esac
+  case $OPT in
+    n)
+      RSYNC_OPTIONS+="--dry-run "
+      ;;
+    v)
+      RSYNC_OPTIONS+="--verbose "
+      ;;
+    h)
+      usage
+      echo
+      echo "  -n  Show what would have been backed up"
+      echo "  -v  Increase verbosity"
+      exit 0
+      ;;
+    \?)
+      echo "${PROG}: illegal option -- $OPTARG"
+      usage
+      exit 1
+      ;;
+    :)
+      echo "${PROG}: -${OPTARG} requires an argument"
+      usage
+      exit 1
+      ;;
+  esac
 done
 shift $((OPTIND-1))
 
 if [[ $# -gt 0 ]]; then
-    echo "${PROG}: illegal argument -- $1"
-    usage
-    exit 1
+  echo "${PROG}: illegal argument -- $1"
+  usage
+  exit 1
 fi
 
 # Check rsync version.
@@ -67,28 +67,33 @@ fi
 
 # Ensure that iTunes is not running.
 if [[ "$(osascript -e 'tell application "System Events" to (name of processes) contains "iTunes"')" = "true" ]]; then
-    echo "${PROG}: Quit iTunes before making a backup"
-    exit 1
+  echo "${PROG}: Quit iTunes before making a backup"
+  exit 1
 fi
+
+echo "[$(date "+%Y-%m-%d %H:%M:%S")]: Begin iTunes Backup"
 
 # Backup.
 rsync $RSYNC_OPTIONS \
-    --archive \
-    --delete \
-    --delete-excluded \
-    --exclude ".DS_Store" \
-    --exclude "Cache/" \
-    --hard-links \
-    --acls \
-    --hfs-compression \
-    --protect-decmpfs \
-    --prune-empty-dirs \
-    --stats \
-    --log-file=${HOME}/Library/Logs/${PROG}.log \
-    "$SRC" "$DST"
+  --archive \
+  --hard-links \
+  --acls \
+  --hfs-compression \
+  --protect-decmpfs \
+  --delete \
+  --delete-excluded \
+  --exclude ".DS_Store" \
+  --exclude "Cache/" \
+  --prune-empty-dirs \
+  --log-file=${HOME}/Library/Logs/${PROG}.log \
+  "$SRC" "$DST"
 
 EXITCODE=$?
 if [[ $EXITCODE -ne 0 ]]; then
-    echo "${PROG}: rsync: Error $EXITCODE"
-    exit $EXITCODE
+  echo "[$(date "+%Y-%m-%d %H:%M:%S")]: rsync: Error $EXITCODE"
+  echo "[$(date "+%Y-%m-%d %H:%M:%S")]: End iTunes Backup"
+  exit $EXITCODE
 fi
+
+echo "[$(date "+%Y-%m-%d %H:%M:%S")]: End iTunes Backup"
+
