Move rsync version check after option parsing

diff --git a/scripts/backup-itunes b/scripts/backup-itunes
--- a/scripts/backup-itunes
+++ b/scripts/backup-itunes
@@ -17,9 +17,6 @@ usage() {
 PROG=${0##*/}
 RSYNC_OPTIONS=""
 
-# Check rsync version.
-[[ $(rsync --version) =~ version\ 3\.1 ]] || { echo "$PROG: rsync 3.1.0 or later is required"; exit 1; }
-
 # Make sure to set the DST variable to the destination backup directory.
 DST="/Volumes/Vault/Backup/${HOSTNAME}${HOME}/Music/"
 SRC="${HOME}/Music/iTunes"
@@ -60,6 +57,9 @@ if [[ $# -gt 0 ]]; then
     usage
     exit 1
 fi
+
+# Check rsync version.
+[[ $(rsync --version) =~ version\ 3\.1 ]] || { echo "$PROG: rsync 3.1.0 or later is required"; exit 1; }
 
 # Check if required directories exist.
 [[ -d "$SRC" ]] || { echo "${PROG}: ${SRC}: No such directory"; exit 1; }
